[package]
name = "hancoin"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.52.3", features = ["gossipsub", "tcp", "dns", "websocket", "tokio", "noise", "yamux"] }
warp = "0.3.6"
futures = "0.3.30"
tokio = { version = "1.38.1", features = ["rt-multi-thread", "net", "io-util", "macros", "sync"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
dashmap = "5.5.3"
rand = "0.8.5"
rand_core = "0.6.4"
ed25519-dalek = { version = "1.0.1", features = ["rand_core"] }
parking_lot = "0.12.3"
log = "0.4.21"
env_logger = "0.11.3"