name: Build hancoin

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: 'stable'

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release